### ISSUE TITLE
"empty" page 

### ISSUE THREAD

**Issue by ArcTanSusan** [pybee/podium#1]
https://github.com/pybee/remarkable is a 404 page when you click on "Source Code" on this web page: 
<img width="394" alt="screen shot 2016-07-05 at 8 40 51 pm" src="https://cloud.githubusercontent.com/assets/954858/16607384/3f8818fa-42f5-11e6-826d-340f994e2212.png">

**Comment by freakboy3742** [comment]
@ArcTanSusan Thanks for the report - This is a known issue; I'm working on cleaning up the code for a public release.

**Comment by freakboy3742** [comment]
Closing; the page is no longer empty. Can't say it *does* anything yet... but I'm working on that. :-)
