### ISSUE TITLE
RTD link provides wrong documentation.

### ISSUE THREAD

**Issue by Barbosabyte** [pybee/podium#2]
The link [http://podium.readthedocs.io](http://podium.readthedocs.io) for the documentation in README.rst links to the documentation to another project. 

From their overview:
> What is Podium? Podium is a blazing-fast HTTP Leaderboard service. It could be used to manage any number of leaderboards of people or groups, but our aim is players in a game.
Podium allows easy creation of different types of leaderboards with no set-up involved. Create seasonal, localized leaderboards just by varying their names.

While I know that the name for the project has changed (just yesterday it had another name) and it may not be the one used for final release, this can be confusing and lead to embarrassing situations, especially for newcomers.

**Comment by freakboy3742** [comment]
Gah.. thanks for that heads up. I'll need to work out how to point to a different repo in RTD.
