### ISSUE TITLE
Fix the installation for Kali Linux

### ISSUE THREAD

**Issue by rsip22** [pybee/podium#7]
When I tried to install Podium on Kali, I got an error with the following message:

```
Could not find a version that satisfies the requirement podium (from versions: )
No matching distribution found for podium
```

**Comment by freakboy3742** [comment]
We haven't pushed a version of Podium to PyPI; it's an app, so PyPI isn't the right medium for distribution. I've recently updated the README to reflect this. 

We've also got a problem running on Linux; See #11 for details.
